"""Move pot size and rake to hand table

Revision ID: 0c7017ffb2ca
Revises: 7d12c97e41be
Create Date: 2025-10-14 15:10:11.886194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c7017ffb2ca'
down_revision: Union[str, None] = '7d12c97e41be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('hand', sa.Column('total_pot_size', sa.Float(), nullable=False))
    op.add_column('hand', sa.Column('rake_amount', sa.Float(), nullable=False))
    op.drop_column('hand_player', 'rake_amount')
    op.drop_column('hand_player', 'total_pot_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hand_player', sa.Column('total_pot_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('hand_player', sa.Column('rake_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('hand', 'rake_amount')
    op.drop_column('hand', 'total_pot_size')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
