"""Redesign hand and hand_user

Revision ID: 49f80145e39e
Revises: b00e6dc3cfbf
Create Date: 2025-10-12 20:24:31.958121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49f80145e39e'
down_revision: Union[str, None] = 'b00e6dc3cfbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('hand', sa.Column('site', sa.String(length=32), nullable=False, default="add me"))
    op.add_column('hand', sa.Column('stakes', sa.String(length=32), nullable=False, default="add me"))
    op.add_column('hand', sa.Column('table_name', sa.String(length=32), nullable=False, default="add me"))
    op.add_column('hand', sa.Column('went_to_showdown', sa.Boolean(), nullable=False, default="add me"))
    op.add_column('hand', sa.Column('flop_cards', sa.JSON(), nullable=True))
    op.add_column('hand', sa.Column('turn_card', sa.String(), nullable=True))
    op.add_column('hand', sa.Column('river_card', sa.String(), nullable=True))
    op.alter_column('hand', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('hand_user', 'turn_card')
    op.drop_column('hand_user', 'went_to_showdown')
    op.drop_column('hand_user', 'stakes')
    op.drop_column('hand_user', 'river_card')
    op.drop_column('hand_user', 'table_name')
    op.drop_column('hand_user', 'site')
    op.drop_column('hand_user', 'flop_cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hand_user', sa.Column('flop_cards', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('hand_user', sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('hand_user', sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('hand_user', sa.Column('river_card', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('hand_user', sa.Column('stakes', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('hand_user', sa.Column('went_to_showdown', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('hand_user', sa.Column('turn_card', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('hand', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('hand', 'river_card')
    op.drop_column('hand', 'turn_card')
    op.drop_column('hand', 'flop_cards')
    op.drop_column('hand', 'went_to_showdown')
    op.drop_column('hand', 'table_name')
    op.drop_column('hand', 'stakes')
    op.drop_column('hand', 'site')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
