"""Account foreign key in session

Revision ID: dd5f3dbbdcf3
Revises: fab79094b48d
Create Date: 2025-10-12 20:56:01.918161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5f3dbbdcf3'
down_revision: Union[str, None] = 'fab79094b48d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('account', sa.String(), nullable=False))
    op.create_foreign_key(None, 'session', 'account', ['account'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'account')
    # ### end Alembic commands ###
