"""added ev column

Revision ID: f4e41c80dc13
Revises: 89530d30c845
Create Date: 2025-10-30 15:19:26.942024

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4e41c80dc13'
down_revision: Union[str, None] = '89530d30c845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('hand_player', sa.Column('ev_pre', sa.Float(), nullable=True))
    op.add_column('hand_player', sa.Column('ev_flop', sa.Float(), nullable=True))
    op.add_column('hand_player', sa.Column('ev_turn', sa.Float(), nullable=True))
    op.add_column('hand_player', sa.Column('ev_river', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hand_player', 'ev_river')
    op.drop_column('hand_player', 'ev_turn')
    op.drop_column('hand_player', 'ev_flop')
    op.drop_column('hand_player', 'ev_pre')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
