"""Integrating poker bankroll

Revision ID: fab79094b48d
Revises: 49f80145e39e
Create Date: 2025-10-12 20:53:28.562879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab79094b48d'
down_revision: Union[str, None] = '49f80145e39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('live', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('category',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('game',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stakes', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cash_in', sa.Float(), nullable=False),
    sa.Column('cash_out', sa.Float(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bullets', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['game.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hand', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('player', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('player', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'updated_at')
    op.drop_column('player', 'created_at')
    op.drop_column('hand', 'updated_at')
    op.drop_table('session')
    op.drop_table('game')
    op.drop_table('category')
    op.drop_table('account')
    # ### end Alembic commands ###
